/* Auth Types */
export const ADD_NAME = 'ADD_NAME';
export const ADD_EMAIL = 'ADD_EMAIL';
export const ADD_PASSWORD = 'ADD_PASSWORD';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER';
export const FAILURE_REGISTER = 'FAILURE_REGISTER';
export const SIGN_IN_LOADING = 'SIGN_IN_LOADING';
export const SIGN_UP_LOADING = 'SIGN_UP_LOADING';

/* Application Types */
export const ADD_CONTACT = 'ADD_CONTACT';
export const ADD_NEW_CONTACT_ERROR = 'ADD_NEW_CONTACT_ERROR';
export const ADD_NEW_CONTACT_SUCCESS = 'ADD_NEW_CONTACT_SUCCESS';

export const CONTACTS_LIST = 'CONTACTS_LIST';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const FETCH_ALL_CHATS = 'FETCH_ALL_CHATS';


export const LIST_CONVERSATION_USER = 'LIST_CONVERSATION_USER';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
